export const typeDeclarations = `// generated by cppbind.ts from functions marked with [[ZIG_EXPORT(mode)]]

const fun = @import("fun");
const jsc = fun.jsc;
const HTTPServerAgent = fun.jsc.Debugger.HTTPServerAgent;
const Environment = fun.Environment;
`;

export const sharedTypes: Record<string, string> = {
  // Basic types
  "bool": "bool",
  "char": "u8",
  "unsigned char": "u8",
  "signed char": "i8",
  "char16_t": "u16",
  "short": "c_short",
  "unsigned short": "c_ushort",
  "int": "c_int",
  "unsigned": "c_uint",
  "unsigned int": "c_uint",
  "long": "c_long",
  "unsigned long": "c_ulong",
  "long long": "c_longlong",
  "unsigned long long": "c_ulonglong",
  "float": "f32",
  "double": "f64",
  "size_t": "usize",
  "ssize_t": "isize",
  "int8_t": "i8",
  "uint8_t": "u8",
  "int16_t": "i16",
  "uint16_t": "u16",
  "int32_t": "i32",
  "uint32_t": "u32",
  "int64_t": "i64",
  "uint64_t": "u64",

  // Common Fun types
  "FunString": "fun.String",
  "JSC::EncodedJSValue": "jsc.JSValue",
  "EncodedJSValue": "jsc.JSValue",
  "JSC::JSGlobalObject": "jsc.JSGlobalObject",
  "ZigException": "jsc.ZigException",
  "Inspector::InspectorHTTPServerAgent": "HTTPServerAgent.InspectorHTTPServerAgent",
  "HotReloadId": "HTTPServerAgent.HotReloadId",
  "ServerId": "HTTPServerAgent.ServerId",
  "Route": "HTTPServerAgent.Route",
  "Zig::GlobalObject": "jsc.JSGlobalObject",
  "JSC::VM": "jsc.VM",
  "WTF::StringImpl": "fun.WTF._StringImplStruct",
  "WebCore::DOMURL": "fun.DOMURL",
  "ZigString": "fun.jsc.ZigString",
  "JSC::JSPromise": "fun.jsc.JSPromise",
  "JSC::JSMap": "fun.jsc.JSMap",
  "JSC::CustomGetterSetter": "fun.jsc.CustomGetterSetter",
  "JSC::SourceProvider": "fun.jsc.SourceProvider",
  "JSC::CallFrame": "fun.jsc.CallFrame",
  "JSC::JSObject": "fun.jsc.JSObject",
  "JSC::JSString": "fun.jsc.JSString",
  "JSC::Exception": "fun.jsc.Exception",
  "JSC::JSInternalPromise": "fun.jsc.JSInternalPromise",
  "WebCore::EventLoopTask": "fun.jsc.CppTask",
};

export const bannedTypes: Record<string, string> = {
  "JSC::JSValue": "Not allowed, use JSC::EncodedJSValue instead",
};
