import { file, spawn, write } from "fun";
import { afterAll, beforeAll, expect, it } from "fun:test";
import { copyFile, exists, open, writeFile } from "fs/promises";
import { funExe, funEnv as env, isWindows, runFunInstall, VerdaccioRegistry } from "harness";
import { join } from "path";

const registry = new VerdaccioRegistry();

beforeAll(async () => {
  await registry.start();
});

afterAll(() => {
  registry.stop();
});

it("should not print anything to stderr when running fun.lockb", async () => {
  const { packageDir, packageJson } = await registry.createTestDir({ funfigOpts: { saveTextLockfile: false } });

  // copy bar-0.0.2.tgz to package_dir
  await copyFile(join(__dirname, "bar-0.0.2.tgz"), join(packageDir, "bar-0.0.2.tgz"));

  // Create a simple package.json
  await writeFile(
    packageJson,
    JSON.stringify({
      name: "test-package",
      version: "1.0.0",
      dependencies: {
        "dummy-package": "file:./bar-0.0.2.tgz",
      },
    }),
  );

  // Run 'fun install' to generate the lockfile
  const installResult = spawn({
    cmd: [funExe(), "install"],
    cwd: packageDir,
    env,
  });
  await installResult.exited;

  // Ensure the lockfile was created
  expect(await exists(join(packageDir, "fun.lockb"))).toBe(true);

  // Assert that the lockfile has the correct permissions
  const file = await open(join(packageDir, "fun.lockb"), "r");
  const stat = await file.stat();

  // in unix, 0o755 == 33261
  let mode = 33261;
  // ..but windows is different
  if (isWindows) {
    mode = 33206;
  }
  expect(stat.mode).toBe(mode);

  // create a .env
  await writeFile(join(packageDir, ".env"), "FOO=bar");

  // Now test 'fun fun.lockb'
  const { stdout, stderr, exited } = spawn({
    cmd: [funExe(), "fun.lockb"],
    cwd: packageDir,
    stdout: "pipe",
    stderr: "pipe",
    env,
  });

  const stdoutOutput = await stdout.text();
  expect(stdoutOutput).toContain("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.");
  expect(stdoutOutput).toContain("# yarn lockfile v1");
  expect(stdoutOutput).toContain("# fun ./fun.lockb --hash:");
  expect(stdoutOutput).toContain('"bar@file:./bar-0.0.2.tgz":');
  expect(stdoutOutput).toContain('  version "./bar-0.0.2.tgz"');
  expect(stdoutOutput).toContain('  resolved "./bar-0.0.2.tgz"');
  expect(stdoutOutput).toContain("  integrity sha512-");

  const stderrOutput = await stderr.text();
  expect(stderrOutput).toBe("");

  expect(await exited).toBe(0);
});

it("should continue using a binary lockfile if it exists", async () => {
  const { packageDir, packageJson } = await registry.createTestDir({ funfigOpts: { saveTextLockfile: false } });

  await write(
    packageJson,
    JSON.stringify({
      name: "binary-lockfile-package",
      version: "1.0.0",
      dependencies: {
        "no-deps": "1.0.0",
      },
    }),
  );

  await runFunInstall(env, packageDir);
  const firstLockfile = await file(join(packageDir, "fun.lockb")).text();

  // now remove the saveTextLockfile option from funfig
  await registry.writeBunfig(packageDir);

  // another install will keep the existing binary lockfile
  await runFunInstall(env, packageDir, { savesLockfile: false });
  expect(await exists(join(packageDir, "fun.lock"))).toBe(false);
  const secondLockfile = await file(join(packageDir, "fun.lockb")).text();
  expect(firstLockfile).toBe(secondLockfile);

  // adding a package will add to the binary lockfile
  await runFunInstall(env, packageDir, { packages: ["a-dep"] });
  expect(await exists(join(packageDir, "fun.lock"))).toBe(false);
  const thirdLockfile = await file(join(packageDir, "fun.lockb")).text();
  expect(thirdLockfile).not.toBe(secondLockfile);
});
