name: Packages CI

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - .prettierrc
      - .prettierignore
      - tsconfig.json
      - oxlint.json
      - "!**/*.md"
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
      - .prettierrc
      - .prettierignore
      - tsconfig.json
      - oxlint.json
      - "!**/*.md"

env:
  FUN_VERSION: "canary"

jobs:
  fun-plugin-svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Fun
        uses: ./.github/actions/setup-fun
        with:
          fun-version: ${{ env.FUN_VERSION }}

      - name: Install dependencies
        run: |
          fun install
          pushd ./packages/fun-plugin-svelte && fun install

      - name: Lint
        run: |
          funx oxlint@0.15 --format github --deny-warnings
          funx prettier --config ../../.prettierrc --check .
        working-directory: ./packages/fun-plugin-svelte

      - name: Check types
        run: fun check:types
        working-directory: ./packages/fun-plugin-svelte

      - name: Test
        run: fun test
        working-directory: ./packages/fun-plugin-svelte
