name: VSCode Extension Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g. 0.0.25) - Check the marketplace for the latest version"
        required: true
        type: string

jobs:
  publish:
    name: "Publish to VS Code Marketplace"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Fun
        uses: ./.github/actions/setup-fun
        with:
          fun-version: "1.2.18"

      - name: Install dependencies (root)
        run: fun install

      - name: Install dependencies
        run: fun install
        working-directory: packages/fun-vscode

      - name: Set Version
        run: fun pm version ${{ github.event.inputs.version }} --no-git-tag-version --allow-same-version
        working-directory: packages/fun-vscode

      - name: Build (inspector protocol)
        run: fun install && fun run build
        working-directory: packages/fun-inspector-protocol

      - name: Build (vscode extension)
        run: fun run build
        working-directory: packages/fun-vscode

      - name: Publish
        if: success()
        run: funx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCODE_EXTENSION }}
        working-directory: packages/fun-vscode/extension

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: fun-vscode-${{ github.event.inputs.version }}.vsix
          path: packages/fun-vscode/extension/fun-vscode-${{ github.event.inputs.version }}.vsix
